Update commit-msg hook
Because not everyone wants the branch name appended to the commit msg
this behavior now depends on a git config setting that can be set to
true or false: git-hooks.append-branch-name.

The default behavior is that nothing gets appended because the config is
not set.

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -107,10 +107,12 @@ sed -i.bak '/^#/ d' $1
 sed -i.bak -e :a -e '/^\n*$/{$d;N;ba' -e '}' $1
 
 # Append the branch name to the commit message
-branch="$(git symbolic-ref --short HEAD)"
-if [[ -z "${branch}" ]]; then
-    echo "${error_msg} Could not determine the branch name"
-    exit 1
-fi
+append_branch_name=$(git config --get git-hooks.append-branch-name)
+if [[ -n "${append_branch_name}" ]] && [[ "${append_branch_name}" = true ]]; then
+    branch="$(git symbolic-ref --short HEAD)"
+    if [[ -z "${branch}" ]]; then
+        echo "${error_msg} Could not determine the branch name"
+        exit 1
+    fi
 
 echo "[branch: ${branch}]" >> "${1}"
